from pathlib import Path

p = Path("yt_commenter.py")
s = p.read_text(encoding="utf-8")

old_block = """async def comment_on_video(page, video_url: str, comment_text: str) -> None:\n    logging.info("Opening video: %s", video_url)\n    await page.goto(video_url, wait_until="networkidle")\n    logging.info("Scrolling down %d px.", SCROLL_DISTANCE)\n    await page.mouse.wheel(0, SCROLL_DISTANCE)\n    await page.wait_for_timeout(3000)\n\n    clicked = False\n    for selector in COMMENT_PLACEHOLDERS:\n        try:\n            logging.info("Trying comment placeholder: %s", selector)\n            await page.locator(selector).first.click(timeout=5000)\n            clicked = True\n            break\n        except Exception:\n            continue\n    if not clicked:\n        raise RuntimeError("Could not locate comment placeholder.")\n\n    logging.info("Waiting for comment editor.")\n    await page.locator(COMMENT_INPUT_SELECTOR).wait_for(state="visible", timeout=10000)\n    await page.locator(COMMENT_INPUT_SELECTOR).fill(comment_text)\n    delay_ms = random.randint(1800, 4200)\n    logging.info("Waiting human-like delay: %d ms", delay_ms)\n    await page.wait_for_timeout(delay_ms)\n    logging.info("Submitting comment.")\n    await page.locator(SUBMIT_SELECTOR).click(timeout=10000)\n"""
new_block = """async def comment_on_video(page, video_url: str, comment_text: str) -> None:\n    logging.info("Opening video: %s", video_url)\n    await page.goto(video_url, wait_until="domcontentloaded")\n    await page.wait_for_timeout(5000)\n    logging.info("Scrolling down %d px.", SCROLL_DISTANCE)\n    await page.mouse.wheel(0, SCROLL_DISTANCE)\n    await page.wait_for_timeout(5000)\n\n    placeholder_locator = None\n    for selector in COMMENT_PLACEHOLDERS:\n        try:\n            logging.info("Trying comment placeholder: %s", selector)\n            locator = page.locator(selector).first\n            await locator.wait_for(state="visible", timeout=8000)\n            await locator.click(timeout=8000)\n            placeholder_locator = locator\n            break\n        except Exception:\n            continue\n    if placeholder_locator is None:\n        try:\n            frame_locator = page.frame_locator(\"iframe\").locator(COMMENT_PLACEHOLDERS[0]).first\n            await frame_locator.wait_for(state=\"visible\", timeout=8000)\n            await frame_locator.click(timeout=8000)\n            placeholder_locator = frame_locator\n        except Exception:\n            raise RuntimeError(\"Could not locate comment placeholder.\")\n\n    logging.info(\"Waiting for comment editor.\")\n    editor = page.locator(COMMENT_INPUT_SELECTOR).first\n    await editor.wait_for(state=\"visible\", timeout=15000)\n    await editor.click(timeout=10000)\n    await editor.fill(comment_text)\n    delay_ms = random.randint(1800, 4200)\n    logging.info(\"Waiting human-like delay: %d ms\", delay_ms)\n    await page.wait_for_timeout(delay_ms)\n    logging.info(\"Submitting comment.\")\n    await page.locator(SUBMIT_SELECTOR).first.click(timeout=10000)\n"""
if old_block in s:
    s = s.replace(old_block, new_block)

p.write_text(s, encoding="utf-8")
print("patched placeholder logic")
